---
# https://docs.ansible.com/ansible/2.9/modules/modules_by_category.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#playbooks-conditionals
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#playbooks-loops
  - name: Verificar ferramentas
    hosts: all
    tasks:
        - name: Verificar Python
          shell: |
            python3 --version
            pip3 --version
          args:
            executable: /bin/bash
        #  register: out
        #  
        #- debug: resultado=out.stdout_lines
        
          register: log
        
        - debug: msg="{{ log.stdout_lines }}"