- hosts: all
  tasks:
  - name: Criar o arquivo ~/ip para pegar o IP da maquina
    ansible.builtin.copy:
      dest: "~/ip"
      content: |
        curl checkip.amazonaws.com
  - name: Mudar a permissao do arquivo ~/ip
    ansible.builtin.file:
      path: ~/ip
      mode: u+rwx,g+rwx,o+rx
  - name: Instalar lista de pacotes
    become: yes
    yum:
      name:
        - python3
        - python3-pip
        #- python3-venv
        - wget
        - git
      state: present
      lock_timeout: 180
  - name: Preparar utilitário ccat
    ansible.builtin.shell: |
      wget https://github.com/jingweno/ccat/releases/download/v1.1.0/linux-amd64-1.1.0.tar.gz
      tar -zxvf linux-amd64-1.1.0.tar.gz 
      chmod +x linux-amd64-1.1.0/ccat
      sudo mv linux-amd64-1.1.0/ccat /usr/local/bin/ccat
      echo "alias cat='/usr/local/bin/ccat --bg=dark'" | sudo tee -a /etc/profile
      rm -rf linux-amd64-1.1.0*
    args:
      executable: /bin/bash
  - name: Criar diretorio vazio das credenciais da AWS
    ansible.builtin.file:
      path: ~/.aws
      state: directory
      mode: '0755'
  - name: Criar arquivo vazio das credenciais da AWS
    ansible.builtin.file:
      path: ~/.aws/credentials
      state: touch
      mode: u+rw,g+rw,o+rw
  #- name: Criar usuario 'fiap' e anexar ao grupo 'root'
  #  become: yes
  #  ansible.builtin.user:
  #    name: fiap
  #    password: "fi7qgu63oQxIU"
  #    shell: /bin/bash
  #    groups: adm,wheel
  #    append: yes
  # https://www.ktexperts.com/how-to-configure-ssh-password-authentication-for-amazon-ec2-instance/
  # https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
  # https://stackoverflow.com/questions/19292899/creating-a-new-user-and-password-with-ansible
  #- name: Liberar o acesso SSH por autenticacao simples
  #  become: yes
  #  ansible.builtin.shell: |
  #    sed -i 's|PasswordAuthentication no|PasswordAuthentication yes|' /etc/ssh/sshd_config
  #    echo 'ClientAliveInterval 60' | sudo tee --append /etc/ssh/sshd_config
  #  args:
  #    executable: /bin/bash
  #- name: Restartar o daemon SSH service
  #  service:
  #    name: sshd
  #    state: restarted
  #    enabled: yes
  #  become: yes