---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html
  - name: Ajustar hostname das VMs
    hosts: all
    become: yes
    tasks:
        - name: Set hostname
          ansible.builtin.hostname:
            name: "{{ inventory_hostname }}"
            #name: "{{ nome | default('fiap') }}"
            #name: "{{ hostvars[item]['ansible_hostname']}}"
          #with_items: "{{groups['nodes']}}"
          #when: inventory_hostname == "{{ item }}"
          #when: 'inventory_hostname == item|string'