- hosts: all
  tasks:
  - name: Instalar versao especifica do kubeadm, kubectl e kubelet
    ansible.builtin.shell: |
      VERSAO = {{ versao | default('1.17.11') }}
      wget https://storage.googleapis.com/kubernetes-release/release/v$VERSAO/bin/linux/amd64/kubectl
      wget https://storage.googleapis.com/kubernetes-release/release/v$VERSAO/bin/linux/amd64/kubeadm
      wget https://storage.googleapis.com/kubernetes-release/release/v$VERSAO/bin/linux/amd64/kubelet

      chmod +x kubectl
      chmod +x kubeadm
      chmod +x kubelet

      sudo mv kubectl /usr/bin
      sudo mv kubeadm /usr/bin
      sudo mv kubelet /usr/bin
    args:
      executable: /bin/bash
