---
# https://longhorn.io/docs/1.2.0/deploy/install/

  - name: Instalação via Kubeadm do Kubernetes
    hosts: node0
    become: yes
    tasks:
        - name: Configurar storageclass usando longhorn.io
          shell: |
            sudo kubeadm init --control-plane-endpoint $(curl checkip.amazonaws.com):6443
            #	Configurar o cliente kubectl:
            mkdir -p $DIRETORIO/.kube
            sudo cp -i /etc/kubernetes/admin.conf $DIRETORIO/.kube/config
            sudo chown $(id -u):$(id -g) $DIRETORIO/.kube/config
          args:
            executable: /bin/bash

    tasks:
        - name: Configurando network do Kubernetes
          shell: |
            # Configurar a rede (pod network) no Master:
            kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
            # Executar Ferramenta Gráfica de administração da Weave Works:
            kubectl apply -f "https://cloud.weave.works/k8s/scope.yaml?k8s-service-type=NodePort&k8s-version=$(kubectl version | base64 | tr -d '\n')"
            kubectl get svc -n weave
          args:
            executable: /bin/bash
            
# TODO: get token:
# sudo kubeadm token create --print-join-command
