# You can define variables when you run your playbook by passing variables at the command line using the --extra-vars (or -e) argument. 
# When you pass variables at the command line, use a single quoted string, that contains one or more variables, in one of the formats below.
# > ansible-playbook ~/environment/config/ansible/k8s_version_install.yaml  --extra-vars "versao=1.20.1" --inventory hosts -u ec2-user --key-file ~/environment/labsuser.pem

- hosts: all
  tasks:
  - name: Instalar versao especifica do kubeadm, kubectl e kubelet
    ansible.builtin.shell: |
      wget https://storage.googleapis.com/kubernetes-release/release/v"{{ versao | default('1.17.11') }}"/bin/linux/amd64/kubectl
      wget https://storage.googleapis.com/kubernetes-release/release/v"{{ versao | default('1.17.11') }}"/bin/linux/amd64/kubeadm
      wget https://storage.googleapis.com/kubernetes-release/release/v"{{ versao | default('1.17.11') }}"/bin/linux/amd64/kubelet

      chmod +x kubectl
      chmod +x kubeadm
      chmod +x kubelet

      sudo mv kubectl /usr/bin
      sudo mv kubeadm /usr/bin
      sudo mv kubelet /usr/bin
    args:
      executable: /bin/bash
